version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    triggers:
      - schedule:
          filters:
            branches:
              only:
                - master

    jobs:
      - node/test
